In [1]:
#sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [2]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
#Vocabulary size
voc_size=1000

# One Hot Representation

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[383, 625, 948, 643], [383, 625, 948, 781], [383, 179, 948, 106], [284, 824, 952, 311, 205], [284, 824, 952, 311, 543], [993, 383, 98, 948, 383], [703, 90, 296, 311]]


# Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0   0   0 383 625 948 643]
 [  0   0   0   0   0   0 383 625 948 781]
 [  0   0   0   0   0   0 383 179 948 106]
 [  0   0   0   0   0 284 824 952 311 205]
 [  0   0   0   0   0 284 824 952 311 543]
 [  0   0   0   0   0 993 383  98 948 383]
 [  0   0   0   0   0   0 703  90 296 311]]


In [10]:
#features
dim=10

In [11]:
model=Sequential()

model.add(Embedding(voc_size,10,input_length=sent_length))

model.compile("adam","mse")

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 10)            10000     
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153
    0.03952244 -0.04525255 -0.01155223  0.02043441 -0.01379858]
  [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153
    0.03952244 -0.04525255 -0.01155223  0.02043441 -0.01379858]
  [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153
    0.03952244 -0.04525255 -0.01155223  0.02043441 -0.01379858]
  [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153
    0.03952244 -0.04525255 -0.01155223  0.02043441 -0.01379858]
  [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153
    0.03952244 -0.04525255 -0.01155223  0.02043441 -0.01379858]
  [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153
    0.03952244 -0.04525255 -0.01155223  0.02043441 -0.01379858]
  [ 0.033187   -0.00265447 -0.00533607  0.03553224 -0.04248751
   -0.01241679 -0.00364894  0.03159497  0.04007742 -0.02107972]
  [ 0.03869898  0.04532978 -0.03915045  0.00299031 -0.00171062
   -0.04013872 -0.03498287 -0.02190042 -0.045397

In [14]:
embedded_docs[0]

array([  0,   0,   0,   0,   0,   0, 383, 625, 948, 643])

In [16]:
print(model.predict(embedded_docs)[0])

[[-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153  0.03952244
  -0.04525255 -0.01155223  0.02043441 -0.01379858]
 [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153  0.03952244
  -0.04525255 -0.01155223  0.02043441 -0.01379858]
 [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153  0.03952244
  -0.04525255 -0.01155223  0.02043441 -0.01379858]
 [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153  0.03952244
  -0.04525255 -0.01155223  0.02043441 -0.01379858]
 [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153  0.03952244
  -0.04525255 -0.01155223  0.02043441 -0.01379858]
 [-0.04916596 -0.02228547 -0.02669685 -0.00814658 -0.04405153  0.03952244
  -0.04525255 -0.01155223  0.02043441 -0.01379858]
 [ 0.033187   -0.00265447 -0.00533607  0.03553224 -0.04248751 -0.01241679
  -0.00364894  0.03159497  0.04007742 -0.02107972]
 [ 0.03869898  0.04532978 -0.03915045  0.00299031 -0.00171062 -0.04013872
  -0.03498287 -0.02190042 -0.04539759 -0.02369655]
